server:
  port: 8889
  error:
    include-message: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: inventory-service
          uri: ${PRODUCT_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/v1/inventories/**

        - id: order-service
          uri: ${COMMERCE_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/v1/orders/**
          filters:
            - AuthFilter

        - id: cart-service
          uri: ${COMMERCE_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/v1/carts/**
          filters:
            - AuthFilter

        - id: payment-service
          uri: ${COMMERCE_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/v1/payments/**
          filters:
            - AuthFilter

        - id: coupon-service
          uri: ${COMMERCE_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/v1/coupons/**
          filters:
            - AuthFilter

        - id: wishlist-service
          uri: ${COMMERCE_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/v1/wishlist/**
          filters:
            - AuthFilter

        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/user/**

        - id: product-write
          uri: ${PRODUCT_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/v1/products/**,/v1/categories/**,/v1/comments/**
            - Method=POST,PUT,DELETE
          filters:
            - AuthFilter

        - id: product-read
          uri: ${PRODUCT_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/v1/products/**,/v1/categories/**,/v1/comments/**
            - Method=GET

  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health,info
