server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: root
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

rabbitmq:
  exchanges:
    internal: order.exchange
  queues:
    payment-status: payment.status.queue
  routing-keys:
    payment-status: payment.status.updated

payment:
  providers:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY:}
    razorpay:
      key-id: ${RAZORPAY_KEY_ID:}
      key-secret: ${RAZORPAY_KEY_SECRET:}

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
