server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:localhost:5672}

  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: health,info