server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${spring.datasource.url:jdbc:postgresql://postgres:5432/product}
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  elasticsearch:
    rest:
      uris: ${SPRING_ELASTICSEARCH_REST_URIS:http://elasticsearch:9200}
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
  application:
    name: product-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true
