server:
  port: 8081

spring:
  application:
    name: commerce-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/commerce}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

rabbitmq:
  exchanges:
    internal: order.exchange
    notification: notification.exchange
  queues:
    payment-status: payment.status.queue
  routing-keys:
    payment-status: payment.status.updated
    send-email: send.email.routing-key

payment:
  providers:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY:}
    razorpay:
      key-id: ${RAZORPAY_KEY_ID:}
      key-secret: ${RAZORPAY_KEY_SECRET:}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8080}

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      inventoryService:
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info
